# Generated by Django 6.0.3 on 2026-03-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_products", models.IntegerField(default=10)),
                ("max_stores", models.IntegerField(default=1)),
                ("custom_domain", models.BooleanField(default=False)),
                ("analytics", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
            ],
        ),
    ]
