# Generated by Django 6.0.3 on 2026-03-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="accent_color",
            field=models.CharField(default="#E87722", max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="button_style",
            field=models.CharField(default="soft", max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="panel_style",
            field=models.CharField(default="dark", max_length=20),
        ),
    ]
