# Generated by Django 6.0.3 on 2026-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, default="FiPackage", max_length=50),
        ),
    ]
