# Generated by Django 6.0.3 on 2026-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_alter_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="font_accent",
            field=models.CharField(blank=True, default="Syne", max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="font_body",
            field=models.CharField(blank=True, default="DM Sans", max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="font_display",
            field=models.CharField(
                blank=True, default="Cormorant Garamond", max_length=100
            ),
        ),
    ]
