# Generated by Django 6.0.3 on 2026-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_brand_product_material_product_weight_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-is_primary", "order", "id"]},
        ),
    ]
