# Generated by Django 6.0.3 on 2026-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_category"),
        ("stores", "0004_alter_category_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="stores.category"
            ),
        ),
    ]
